name: Deploy hub to GitHub Pages
on:
  push:
    branches: [main]

permissions:          # 👈 add this block (workflow- or job-level)
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: docs          # folder to publish
          publish_branch: gh-pages   # default is fine; adjust if you use a different branch
          github_token: ${{ secrets.PERSONAL_TOKEN }}
